import "./globals.css";
import NavBar from "../Components/NavBar";
import Footer from "../Components/Footer";

import {CrowdFundingProvider} from '../Context/CrowdFunding'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body>
        <CrowdFundingProvider>
        <NavBar />
        <main>{children}</main>
        <Footer />
        </CrowdFundingProvider>
      </body>
    </html>
  );
}
